package AdminPackage;
import ListeEtudiants.EtdPayementListTable;
import com.formdev.flatlaf.FlatLightLaf;
import com.mycompany.gestion_etudiants.ConnectToBD;

import java.io.IOException;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author AdMin
 */
public class Payement extends javax.swing.JFrame {
    
    ConnectToBD connexion;

    /**
     * Creates new form Payement
     * @throws javax.swing.UnsupportedLookAndFeelException
     */
    public Payement() throws UnsupportedLookAndFeelException{
        UIManager.setLookAndFeel( new FlatLightLaf() );
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jTextField1 = new javax.swing.JTextField();
        jSlider1 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        PayementEtdPrenomField = new javax.swing.JTextField();
        PayementPrenomEtdLabel = new javax.swing.JLabel();
        PayementEtdIDLabel = new javax.swing.JLabel();
        recordPaymentBtn = new javax.swing.JButton();
        PayementLevelLabel = new javax.swing.JLabel();
        PayementFiliereLabel = new javax.swing.JLabel();
        PayementEtdIDField = new javax.swing.JTextField();
        PayementEtdIDLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PeriodeComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        MontantSpiner = new javax.swing.JSpinner();
        PayementEtdNameLabel = new javax.swing.JLabel();
        PayementEtdNameField = new javax.swing.JTextField();
        DateSpiner = new javax.swing.JSpinner();
        PayementLevelField = new javax.swing.JTextField();
        PayementOptionField = new javax.swing.JTextField();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Système de Gestion des étudiants");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Payement");

        PayementEtdPrenomField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        PayementEtdPrenomField.setEnabled(false);

        PayementPrenomEtdLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        PayementPrenomEtdLabel.setText("Prénom");

        PayementEtdIDLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        PayementEtdIDLabel.setText("ID de l'étudiant");

        recordPaymentBtn.setBackground(new java.awt.Color(0, 153, 51));
        recordPaymentBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        recordPaymentBtn.setForeground(new java.awt.Color(255, 255, 255));
        recordPaymentBtn.setText("Ajouter");
        recordPaymentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordPaymentBtnActionPerformed(evt);
            }
        });

        PayementLevelLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        PayementLevelLabel.setText("Niveau");

        PayementFiliereLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        PayementFiliereLabel.setText("Filiere");

        PayementEtdIDField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        PayementEtdIDField.setEnabled(false);

        PayementEtdIDLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        PayementEtdIDLabel1.setText("Date");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Période payée");

        PeriodeComboBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        PeriodeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "< -- Sélectionnez une période -- > ", "Inscription", "Octobre", "Novembre", "Décembre", "Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet" }));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Montant payé");

        MontantSpiner.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        MontantSpiner.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 1.0f));
        MontantSpiner.setToolTipText("");

        PayementEtdNameLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        PayementEtdNameLabel.setText("Nom");

        PayementEtdNameField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        PayementEtdNameField.setEnabled(false);

        DateSpiner.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        DateSpiner.setModel(new javax.swing.SpinnerDateModel());
        DateSpiner.setEnabled(false);

        PayementLevelField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        PayementLevelField.setEnabled(false);

        PayementOptionField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        PayementOptionField.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(recordPaymentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(268, 268, 268))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(PeriodeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(MontantSpiner, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PayementLevelLabel)
                        .addGap(293, 293, 293)
                        .addComponent(PayementFiliereLabel)
                        .addGap(252, 252, 252))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PayementLevelField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(PayementEtdIDLabel)
                                .addComponent(PayementEtdIDField, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                .addComponent(PayementEtdNameLabel)
                                .addComponent(PayementEtdNameField)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(DateSpiner, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(PayementPrenomEtdLabel)
                                    .addComponent(PayementEtdPrenomField, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(PayementEtdIDLabel1)
                                    .addComponent(PayementOptionField))))))
                .addGap(0, 24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PayementEtdIDLabel)
                    .addComponent(PayementEtdIDLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PayementEtdIDField, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(DateSpiner))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PayementPrenomEtdLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PayementEtdNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PayementEtdPrenomField, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(PayementEtdNameField))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PayementFiliereLabel)
                    .addComponent(PayementLevelLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PayementLevelField, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(PayementOptionField))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PeriodeComboBox)
                    .addComponent(MontantSpiner, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(recordPaymentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void recordPaymentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordPaymentBtnActionPerformed

        try {
            connexion = new ConnectToBD();
        } catch (IOException ex) {
            Logger.getLogger(Payement.class.getName()).log(Level.SEVERE, null, ex);
        }

        String PEtdID = PayementEtdIDField.getText();
        String PEtdFirstName = PayementEtdPrenomField.getText();
        String PEtdLastName = PayementEtdNameField.getText();
        String PEtdLevel = PayementLevelField.getText();
        String PEtdOption = PayementOptionField.getText();
        String Periode = (String) PeriodeComboBox.getSelectedItem();
        Float Montant = (Float) MontantSpiner.getValue();

        if (Montant.isNaN() || Montant == 0 || Periode.equals((String) PeriodeComboBox.getItemAt(0))) {
            JOptionPane.showMessageDialog(null, "Les données saisies sont incorrectes !");
        } 
        else {
            String requete1 = "INSERT INTO payement (E_ID, Periode, Montant, Date) VALUES (?, ?, ?, CURRENT_TIMESTAMP)";
            try ( PreparedStatement statement1 = connexion.BDconnexion.prepareStatement(requete1) ) {
                
                statement1.setInt(1, Integer.parseInt(PEtdID));
                statement1.setString(2, Periode);
                statement1.setFloat(3, Montant);
                statement1.executeUpdate();

                RemplirPayementListTable(PEtdOption);

                PeriodeComboBox.setSelectedIndex(0);
                MontantSpiner.setValue(0);

                JOptionPane.showMessageDialog(null, "Paymenent ajouté avec succes !");
            }catch (Exception ex) {
                Logger.getLogger(Payement.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        try {
            new EtudiantInformation();
            EtudiantInformation.InfoEtudiant(AdminPage.getTableClicked().getSelectedRow(), AdminPage.getTableClicked());
        } catch (Exception ex) {
            Logger.getLogger(Payement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_recordPaymentBtnActionPerformed

    private void RemplirPayementListTable(String option) throws Exception{
        
        new EtdPayementListTable();
        if(option.equals("ISI") || option.equals("ISRT")){
            EtdPayementListTable.ISIPayementListTable();
        }
        else{
            EtdPayementListTable.MGEPayementListTable();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner DateSpiner;
    private javax.swing.JSpinner MontantSpiner;
    public static javax.swing.JTextField PayementEtdIDField;
    private javax.swing.JLabel PayementEtdIDLabel;
    private javax.swing.JLabel PayementEtdIDLabel1;
    public static javax.swing.JTextField PayementEtdNameField;
    private javax.swing.JLabel PayementEtdNameLabel;
    public static javax.swing.JTextField PayementEtdPrenomField;
    private javax.swing.JLabel PayementFiliereLabel;
    public static javax.swing.JTextField PayementLevelField;
    private javax.swing.JLabel PayementLevelLabel;
    public static javax.swing.JTextField PayementOptionField;
    private javax.swing.JLabel PayementPrenomEtdLabel;
    private javax.swing.JComboBox<String> PeriodeComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton recordPaymentBtn;
    // End of variables declaration//GEN-END:variables
}
